Repository H-uru/korman, pull requests merged in 2018-08, with the labels that each got.

#104 Fix #22
  korman/operators/__init__.py
  korman/operators/op_modifier.py
  korman/operators/op_texture.py
  korman/operators/op_ui.py
  korman/ui/__init__.py
  korman/ui/modifiers/anim.py
  korman/ui/modifiers/logic.py
  korman/ui/modifiers/render.py
  korman/ui/modifiers/sound.py
  korman/ui/modifiers/water.py
  korman/ui/ui_list.py
  korman/ui/ui_texture.py
Labels: enhancement

#113 Fix Volume Sensor typos.
  korman/nodes/node_conditions.py
Labels: defect

#107 Responder State IDs
  korman/nodes/node_core.py
  korman/nodes/node_deprecated.py
  korman/nodes/node_responder.py
  korman/properties/modifiers/region.py
Labels: enhancement

#103 Fix #76
  korman/exporter/material.py
  korman/properties/modifiers/render.py
Labels: enhancement

#105 Cameras
  korman/exporter/animation.py
  korman/exporter/camera.py
  korman/exporter/convert.py
  korman/exporter/utils.py
  korman/helpers.py
  korman/idprops.py
  korman/nodes/node_messages.py
  korman/properties/__init__.py
  korman/properties/modifiers/region.py
  korman/properties/prop_camera.py
  korman/ui/__init__.py
  korman/ui/modifiers/region.py
  korman/ui/ui_camera.py
Labels: enhancement, feature

#114 Fix responder nodes not notifying python nodes
  korman/nodes/node_responder.py
Labels: defect
