Repository H-uru/korman, pull requests merged in 2021-06, with the labels that each got.

#251 Implement the Random Sound modifier.
  korman/exporter/convert.py
  korman/exporter/physics.py
  korman/nodes/node_messages.py
  korman/properties/modifiers/physics.py
  korman/properties/modifiers/sound.py
  korman/ui/modifiers/physics.py
  korman/ui/modifiers/sound.py
Labels: feature

#247 Enable Shadow-only Lamps
  korman/exporter/rtlight.py
Labels: defect

#254 Support for quaternion rotation animations
  korman/exporter/animation.py
  korman/exporter/camera.py
  korman/properties/prop_object.py
Labels: enhancement
